### ISSUE TITLE
Unable to run terraformer on Mac OSX with python-3.8.2

### ISSUE THREAD

**Issue by bpradipt** [ibm-cloud-architecture/terraformer#1]
When running on OSX, I get this error
```➜  terraformer git:(master) ✗ ./releases/download/v1.2.4.1/terraformer/terraformer -h
dyld: Library not loaded: /Library/Frameworks/Python.framework/Versions/3.8/Python
  Referenced from: /Users/bpradipt/Code/src/github.com/terraformer/./releases/download/v1.2.4.1/terraformer/terraformer
  Reason: image not found
```
I'm running OSX Catalina.

Searching in google, hints that python installation could be flawed. However I'm able to run python3.8 and don't see any issues with python install.

Any help to debug this issue ?

**Comment by jaywarfield** [comment]
I recently upgraded to Python 3.8.2 from python.org which installed the framework.  I have seen this issue if Python is installed by other means where the framework was not included even though Python 3.8 could be run.

**Comment by jaywarfield** [comment]
This issue has been seen when Python 3 is installed via the pyenv tool which puts python files in a different set of directories.  I installed Python 3.8.2 from python.org and don't see this issue.  Let me know if this resolves the issue.

**Comment by bpradipt** [comment]
Thanks.. When I installed python from python.org it worked. It didn't work with brew installed python nor with pipenv.
