### ISSUE TITLE
Need help understanding how Terraformer and IBM Cloud Stencils work together.

### ISSUE THREAD

**Issue by ssant0sh** [ibm-cloud-architecture/terraformer#2]
Hi,

As per the terraformer documentation in this repo (**Usage** section), I understand that we can work on a VPC architecture using **IBM Cloud Stencils** [https://github.com/ibm-cloud-architecture/ibm-cloud-stencils] in tools like **IBM IT Architect Assistant** or **JGraph Draw.io** app [https://github.com/jgraph/drawio-desktop/releases] and use the output as input to terraformer from which we can subsequently generate the terraform config files.

**(Steps from documentation reproduced below)**

1. Design your VPC infrastructure using IBM Cloud Stencils.
2. Copy sample files from provided json, ods, xlsx, or yaml folder to your data folder.
3. Customize sample files according to your design.
4. To display command options: bin/terraformer -h
5. To generate with input from data and output to resources: bin/terraformer data
6. Execute terraform in output directory to provision your VPC infrastructure

Now, I imported one of the stencil templates from [https://github.com/ibm-cloud-architecture/ibm-cloud-stencils/tree/master/drawio/templates] into JGraph Draw.io  and saw that the underlying file format of the architecture diagram is XML.

However, in the terraformer documentation, the data folder has input formats like json, ods, xlsx, yaml.

**I need help in understanding how the stencil template (XML) and terraformer input formats are related - specifically steps 1, 2, and 3. Do we need to manually edit the data files based on the stencil work? or is there some way to generate the json from the stencil work?**

**Comment by jaywarfield** [comment]
Hi, Step 1 is mentioned as an optional best practice to design the desired architecture and then (as you mentioned) you will manually edit the data files of your desired data format (json or ods or xlsx or yaml) in the data folder according to your design.  I will clarify this in the README.  Let me know if you have any further questions.  Thanks for your interest in Terraformer and for using IBM Cloud!

**Comment by ssant0sh** [comment]
@jaywarfield, thank you for your response. On a different note, I came across CAM Template Designer as part of the CAM package. Would you be able to give me pointers as to whether the template designer is available as a standalone tool in itself, or will be available only along as part of the complete installer. Thanks, Santosh !
